Short exercises after each video

In [2]:
def increment(n):
    n += 1
    return n                # <------ required to acoid TypeError

n = 1
while n < 10:
    n = increment(n)
print(n)

10


In [3]:
class NewList(list):
    def remove_max(self):
        self.remove(max(self))
    def append_sum(self):
        self.append(sum(self))
                                        # Never stop
x = NewList([1,2,3])
while max(x) < 10:
    x.remove_max()
    x.append_sum()

print(x)

KeyboardInterrupt: 

In [ ]:
def update(n, x):
    n = 2
    x.append(4)
    print('update: ', n, x)

def main():
    n = 1
    x = [0,1,2,3]
    print('main: ', n, x)
    update(n, x)
    print('main: ', n, x)

main()

# Numpy 


In [1]:
import numpy as np 
zeroes_a = np.zeros(5)
zeroes_a


array([0., 0., 0., 0., 0.])

In [1]:
zeroes_b = np.zeros((2,3))
zeroes_b

NameError: name 'np' is not defined

In [14]:
a = np.arange(20)
a.shape                     # 1-D array
a[5] = 10000


In [58]:
b = np.arange(20).reshape(5,4)                # 2-D array with .reshape() 
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [50]:
c = np.arange(0, 50).reshape(5,2,5)     # 3-d array using .reshape()
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [53]:
np.full((4,5),8) # . n*n array with a certain number

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [54]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [60]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [13]:
a = np.array([1,2,3])
a                                       # 1-d array

array([1, 2, 3])

In [28]:
a = np.array([(1,2,3), (4,5,6)])      # 2-d array
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [25]:
np.random.random((2,4))

array([[0.52855284, 0.80970563, 0.63761397, 0.80279896],
       [0.29252121, 0.33576312, 0.76346224, 0.67018637]])

In [32]:
x = np.array([[3,6],[5,7]])
x.transpose()

array([[3, 5],
       [6, 7]])

In [90]:
x = np.array([1,2,3,4,5,6,7])
y = np.array([4,5,6])
X = np.array([[1,2,3], [4,5,6]])
Y = np.array([[3,2,1], [6,5,1]])
Xy = np.arange(0,50).reshape(5,2,5)
                
Xy

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [42]:
x + y

array([[5, 7, 9]])

In [45]:
X + Y

array([[ 4,  4,  4],
       [10, 10,  7]])

# Slicing
#### For 1-D array:
Slice like lists.
#### For 2-D array:
Give start/stop points for row and column separately: x[1:4,3:5,0:]
#### 3-D array:
The first argument is dimension, second row, third column

In [73]:
x[-5:] .   # Slicing is always towards the right

array([3, 4, 5, 6, 7])

In [78]:
X[0:,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
Xy[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
Xy[2:,0:,1:4]           # 3-d slicing .    Just gotta think a little

array([[[21, 22, 23],
        [26, 27, 28]],

       [[31, 32, 33],
        [36, 37, 38]],

       [[41, 42, 43],
        [46, 47, 48]]])